---
mattermost_vars:
  url:         'https://releases.mattermost.com/5.7.1/mattermost-team-5.7.1-linux-amd64.tar.gz'
  checksum:    'sha256:be7ea8c95aeb54921b492cfea5477d9e37b8330550254214aa63546d1c1dda76'
  service:     'mattermost.service'
  user_owner:  'mattermost'
  user_group:  'mattermost'
  root_owner:  'root'
  root_group:  'root'
  base_dir:    '/opt/mattermost'
